ddtregistry:
  restart: always
  image: registry:2.7.0
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/1_docker-registry.9cka.cn_bundle.crt
    REGISTRY_HTTP_TLS_KEY: /certs/2_docker-registry.9cka.cn.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /opt/registry:/var/lib/registry
    - /opt/certs:/certs
    - /opt/auth:/auth
